### ISSUE TITLE
弹框模式的按钮能否绑定验证结果

### ISSUE THREAD

**Issue by xiaoreign** [cipchk/nz-schema-form#19]
![qq 20180205151412](https://user-images.githubusercontent.com/20812513/35792280-4378fc80-0a87-11e8-9051-eac1f2be27ad.png)

**Comment by xiaoreign** [comment]
使用ng-template自定义了<取消><确定>的按钮,,,disabled 是否有一个form的某个值来绑定确认按钮

**Comment by cipchk** [comment]
可以利用 `(isValid)` 监听表单校验状态。
