### ISSUE TITLE
无法加载自定义编辑器

### ISSUE THREAD

**Issue by limingyao-xx** [cipchk/nz-schema-form#20]
异常：![image](https://user-images.githubusercontent.com/2350389/35795915-c2a01d82-0a95-11e8-9404-60987eae91bf.png)

步骤：
按文档 https://cipchk.github.io/nz-schema-form/#/document/customize 操作无法加载编辑器ueditor.widget。

**Comment by cipchk** [comment]
请提供重现示例。

**Comment by limingyao-xx** [comment]
访问路径：
![image](https://user-images.githubusercontent.com/2350389/35796724-6a7a86e4-0a98-11e8-914d-f90764110e7f.png)

示例：
[dm.zip](https://github.com/cipchk/nz-schema-form/files/1694474/dm.zip)

**Comment by cipchk** [comment]
麻烦在 [stackblitz](https://stackblitz.com/edit/nz-schema-form?file=app%2Fapp.component.ts)，谢谢。

**Comment by limingyao-xx** [comment]
https://stackblitz.com/edit/nz-schema-form-selchp?file=app%2Fapp.module.ts

**Comment by cipchk** [comment]
暂时我不清楚是什么原因引起的，我晚上再核实，目前你可以通过，再加载一次，配置信息，应该可以解决。

```ts

import { NZ_SF_USER_OPTIONS_TOKEN, NZ_SF_OPTIONS_TOKEN, DEFAULT } from 'nz-schema-form/schema-form.options';

export function optionsFactory(options: any) {
    return Object.assign(DEFAULT, options);
}

  providers: [
    { provide: NZ_SF_USER_OPTIONS_TOKEN, useValue: {} },
    { provide: NZ_SF_OPTIONS_TOKEN, useFactory: optionsFactory, deps: [NZ_SF_USER_OPTIONS_TOKEN] },
    { provide: WidgetRegistry, useClass: MyWidgetRegistry },],
```
