### ISSUE TITLE
Cannot find type definition file for 'z-schema'

### ISSUE THREAD

**Issue by ghost** [cipchk/nz-schema-form#21]
按文档开始使用，做了一个例子，npm start如下错
ERROR in node_modules/_nz-schema-form@0.0.1-beta.1@nz-schema-form/schema-form.op
tions.d.ts(1,23): error TS2688: Cannot find type definition file for 'z-schema'.

**Comment by cipchk** [comment]
```bash
npm i --save-dev @types/z-schema
```

**Comment by ghost** [comment]
安装types/z-schema已解决
