### ISSUE TITLE
build编译报错

### ISSUE THREAD

**Issue by xiaoreign** [cipchk/nz-schema-form#22]
![image](https://user-images.githubusercontent.com/20812513/36013948-2eb4194c-0da2-11e8-9db0-ae1aabe767f9.png)

**Comment by xiaoreign** [comment]
import { SFSchema } from 'nz-schema-form';
只要一引入这个 就报错

**Comment by cipchk** [comment]
请告知版本信息。

**Comment by xiaoreign** [comment]
angular 5.1.2升级至5.2.4后.编译最后还是有报错

**Comment by xiaoreign** [comment]
node_modules重新安装后解决问题了
