### ISSUE TITLE
按文档添加到ng-alian运行时报错

### ISSUE THREAD

**Issue by ghost** [cipchk/nz-schema-form#23]
ERROR Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'schema' since it isn't a known property of 'nz-sf'.
1. If 'nz-sf' is an Angular component and it has 'schema' input, then verify that it is part of this module.
2. If 'nz-sf' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
</pro-header>

<nz-sf [ERROR ->][schema]="schema"></nz-sf>"): ng:///DemoTableMgrModule/TableMgrAddComponent.html@17:7

**Comment by cipchk** [comment]
建议在 SharedModule 中导入

**Comment by ghost** [comment]
在shared.module.ts中添加NzSchemaFormModule.forRoot() ，依然报上面错

**Comment by xiaoheng008** [comment]
import中需要forRoot，export不需要forRoot@80631004
