### ISSUE TITLE
采用refreshSchema刷新后select宽度变小

### ISSUE THREAD

**Issue by limingyao-xx** [cipchk/nz-schema-form#34]
`@ViewChild('sf') sf: FormComponent;
schema: SFSchema = {
    properties: {
        app: {
            type: 'string',
            title: '附属应用',
            widget: 'select',
            enum: []
        }
    }
};

ngOnInit() {
    this.http.get('/apps').subscribe((res: any) => {
        this.schema.properties.app.enum = res;
        this.sf.refreshSchema();
    });
}`

采用这种方式设置default后，select的宽度变小。如图：

![1](https://user-images.githubusercontent.com/2350389/37270417-b27decce-2609-11e8-8b88-a91a5a33ca9a.png)

**Comment by cipchk** [comment]
这是 ng-zorro-antd 的一个样式BUG，所以最好在 schema 的 widgets 中指定 `style` 内容即可。

**Comment by limingyao-xx** [comment]
测试了下，设置widget的style：‘width：200px’有效，但设置百分比无效。还有其它方案么？

**Comment by cipchk** [comment]
据我所知，没有。
