### ISSUE TITLE
设置字段为“hidden”仍然占据了显示位置

### ISSUE THREAD

**Issue by limingyao-xx** [cipchk/nz-schema-form#36]
![1](https://user-images.githubusercontent.com/2350389/37380486-ee05bdf6-2773-11e8-8b19-143aa7227543.png)

**Comment by cipchk** [comment]
请提供可重现的 Schema，并在 [validator](https://cipchk.github.io/nz-schema-form/#/validator) 得以重现。

**Comment by limingyao-xx** [comment]
```
{
    "span_label_fixed": 100,
    "span": 8,
    "properties": {
        "is_file": {"type": "string", "widget": "hidden"}
    }
}
```

![2](https://user-images.githubusercontent.com/2350389/37380941-c592b840-2775-11e8-927b-b37718c3d0a5.png)

**Comment by cipchk** [comment]
```json
{
    "span_label_fixed": 100,
    "span": 8,
    "properties": {
        "is_file": {"type": "string", "widget": { "type": "hidden" } }
    }
}
```

**Comment by limingyao-xx** [comment]
此处文档可更新下 

![1](https://user-images.githubusercontent.com/2350389/37381537-a2535bf2-2778-11e8-8b73-8a61be6d2c6b.png)
