### ISSUE TITLE
小部件array的样式问题

### ISSUE THREAD

**Issue by xiaoreign** [cipchk/nz-schema-form#37]
版本:0.2.0
![image](https://user-images.githubusercontent.com/20812513/37389512-9c86159e-279f-11e8-89f9-d3314d10078a.png)
如果添加多了会超过,能否往下添加而不是往右边

**Comment by cipchk** [comment]
================================
请务必提供完整可重现的 Schema，务必能通过 https://cipchk.github.io/nz-schema-form/#/validator 得以重现。
为了减少浪费时间；描述不清楚、不符合以下声明规范；会直接关闭。
================================

**Comment by xiaoreign** [comment]
只要在modal,item的数量超过modal本身的宽度 就会超出

**Comment by cipchk** [comment]
@xiaoreign 

> 请务必提供完整可重现的 Schema，务必能通过 https://cipchk.github.io/nz-schema-form/#/validator 得以重现。
> 为了减少浪费时间；描述不清楚、不符合以下声明规范；会直接关闭。
