### ISSUE TITLE
type:object 的样式问题

### ISSUE THREAD

**Issue by liweitao92** [cipchk/nz-schema-form#39]
![image](https://user-images.githubusercontent.com/30191996/37418377-07c8d95c-27ed-11e8-9783-7d1f7a681c7c.png)

-------------------------

![image](https://user-images.githubusercontent.com/30191996/37418381-0c2006ba-27ed-11e8-9317-27b7fd1a9d16.png)

这样设置后，怎样可以让下面的布局跟上面一致？

**Comment by cipchk** [comment]
================================
请务必提供完整可重现的 Schema，务必能通过 https://cipchk.github.io/nz-schema-form/#/validator 得以重现。
为了减少浪费时间；描述不清楚、不符合以下声明规范；会直接关闭。
================================
